# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popupVersion.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(274, 69)
        self.popup_version = QtWidgets.QWidget(MainWindow)
        self.popup_version.setObjectName("popup_version")
        self.popup1_label = QtWidgets.QLabel(self.popup_version)
        self.popup1_label.setGeometry(QtCore.QRect(98, 13, 81, 21))
        self.popup1_label.setObjectName("popup1_label")
        self.popup1_label_2 = QtWidgets.QLabel(self.popup_version)
        self.popup1_label_2.setGeometry(QtCore.QRect(180, 14, 81, 21))
        self.popup1_label_2.setText("")
        self.popup1_label_2.setObjectName("popup1_label_2")
        self.popup1_label_3 = QtWidgets.QLabel(self.popup_version)
        self.popup1_label_3.setGeometry(QtCore.QRect(98, 33, 41, 21))
        self.popup1_label_3.setObjectName("popup1_label_3")
        self.popup1_label_4 = QtWidgets.QLabel(self.popup_version)
        self.popup1_label_4.setGeometry(QtCore.QRect(140, 33, 41, 21))
        self.popup1_label_4.setObjectName("popup1_label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.popup_version)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1, 4, 71, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.popup1_label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.popup1_label_5.setText("")
        self.popup1_label_5.setObjectName("popup1_label_5")
        self.verticalLayout_2.addWidget(self.popup1_label_5)
        MainWindow.setCentralWidget(self.popup_version)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.popup1_label.setText(_translate("MainWindow", "최신 업데이트:"))
        self.popup1_label_3.setText(_translate("MainWindow", "개발자:"))
        self.popup1_label_4.setText(_translate("MainWindow", "송병규"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
