# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowGraphic.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_t1Window2(object):
    def setupUi(self, t1Window2):
        t1Window2.setObjectName("t1Window2")
        t1Window2.resize(920, 639)
        self.tab1_newWindow2 = QtWidgets.QWidget(t1Window2)
        self.tab1_newWindow2.setObjectName("tab1_newWindow2")
        self.tab1_win2label = QtWidgets.QLabel(self.tab1_newWindow2)
        self.tab1_win2label.setGeometry(QtCore.QRect(10, 10, 56, 21))
        self.tab1_win2label.setObjectName("tab1_win2label")
        self.tab1_win2comboBox = QtWidgets.QComboBox(self.tab1_newWindow2)
        self.tab1_win2comboBox.setGeometry(QtCore.QRect(190, 11, 171, 22))
        self.tab1_win2comboBox.setObjectName("tab1_win2comboBox")
        self.tab1_win2comboBox_2 = QtWidgets.QComboBox(self.tab1_newWindow2)
        self.tab1_win2comboBox_2.setGeometry(QtCore.QRect(70, 10, 81, 22))
        self.tab1_win2comboBox_2.setObjectName("tab1_win2comboBox_2")
        self.tab1_win2widget = QtWidgets.QWidget(self.tab1_newWindow2)
        self.tab1_win2widget.setGeometry(QtCore.QRect(10, 40, 901, 591))
        self.tab1_win2widget.setObjectName("tab1_win2widget")
        self.tab1_win2pushButton = QtWidgets.QPushButton(self.tab1_newWindow2)
        self.tab1_win2pushButton.setGeometry(QtCore.QRect(850, 10, 61, 21))
        self.tab1_win2pushButton.setObjectName("tab1_win2pushButton")
        self.tab1_win2label_2 = QtWidgets.QLabel(self.tab1_newWindow2)
        self.tab1_win2label_2.setGeometry(QtCore.QRect(160, 10, 31, 21))
        self.tab1_win2label_2.setObjectName("tab1_win2label_2")
        self.tab1_win2label_3 = QtWidgets.QLabel(self.tab1_newWindow2)
        self.tab1_win2label_3.setGeometry(QtCore.QRect(370, 9, 31, 21))
        self.tab1_win2label_3.setObjectName("tab1_win2label_3")
        self.tab1_win2comboBox_3 = QtWidgets.QComboBox(self.tab1_newWindow2)
        self.tab1_win2comboBox_3.setGeometry(QtCore.QRect(400, 10, 171, 22))
        self.tab1_win2comboBox_3.setObjectName("tab1_win2comboBox_3")
        t1Window2.setCentralWidget(self.tab1_newWindow2)

        self.retranslateUi(t1Window2)
        QtCore.QMetaObject.connectSlotsByName(t1Window2)

    def retranslateUi(self, t1Window2):
        _translate = QtCore.QCoreApplication.translate
        t1Window2.setWindowTitle(_translate("t1Window2", "MainWindow"))
        self.tab1_win2label.setText(_translate("t1Window2", "차트종류"))
        self.tab1_win2pushButton.setText(_translate("t1Window2", "조회"))
        self.tab1_win2label_2.setText(_translate("t1Window2", "x축"))
        self.tab1_win2label_3.setText(_translate("t1Window2", "y축"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    t1Window2 = QtWidgets.QMainWindow()
    ui = Ui_t1Window2()
    ui.setupUi(t1Window2)
    t1Window2.show()
    sys.exit(app.exec_())
