# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowList.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tab3_win1Main(object):
    def setupUi(self, tab3_win1Main):
        tab3_win1Main.setObjectName("tab3_win1Main")
        tab3_win1Main.resize(1056, 583)
        self.tab3_newWindow1 = QtWidgets.QWidget(tab3_win1Main)
        self.tab3_newWindow1.setObjectName("tab3_newWindow1")
        self.tab3_win1tableWidget = QtWidgets.QTableWidget(self.tab3_newWindow1)
        self.tab3_win1tableWidget.setGeometry(QtCore.QRect(10, 30, 1031, 501))
        self.tab3_win1tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab3_win1tableWidget.setAlternatingRowColors(True)
        self.tab3_win1tableWidget.setObjectName("tab3_win1tableWidget")
        self.tab3_win1tableWidget.setColumnCount(0)
        self.tab3_win1tableWidget.setRowCount(0)
        self.tab3_win1label = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label.setGeometry(QtCore.QRect(10, 6, 41, 20))
        self.tab3_win1label.setObjectName("tab3_win1label")
        self.tab3_win1label_2 = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label_2.setGeometry(QtCore.QRect(70, 6, 401, 20))
        self.tab3_win1label_2.setAutoFillBackground(True)
        self.tab3_win1label_2.setText("")
        self.tab3_win1label_2.setObjectName("tab3_win1label_2")
        self.tab3_win1pushButton = QtWidgets.QPushButton(self.tab3_newWindow1)
        self.tab3_win1pushButton.setGeometry(QtCore.QRect(960, 5, 75, 20))
        self.tab3_win1pushButton.setObjectName("tab3_win1pushButton")
        self.tab3_win1label_4 = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label_4.setGeometry(QtCore.QRect(60, 540, 221, 21))
        self.tab3_win1label_4.setAutoFillBackground(True)
        self.tab3_win1label_4.setText("")
        self.tab3_win1label_4.setObjectName("tab3_win1label_4")
        self.tab3_win1label_6 = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label_6.setGeometry(QtCore.QRect(60, 560, 51, 21))
        self.tab3_win1label_6.setAutoFillBackground(True)
        self.tab3_win1label_6.setText("")
        self.tab3_win1label_6.setObjectName("tab3_win1label_6")
        self.tab3_win1label_3 = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label_3.setGeometry(QtCore.QRect(20, 540, 41, 21))
        self.tab3_win1label_3.setObjectName("tab3_win1label_3")
        self.tab3_win1label_7 = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label_7.setGeometry(QtCore.QRect(120, 560, 41, 21))
        self.tab3_win1label_7.setObjectName("tab3_win1label_7")
        self.tab3_win1label_8 = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label_8.setGeometry(QtCore.QRect(160, 560, 141, 21))
        self.tab3_win1label_8.setAutoFillBackground(True)
        self.tab3_win1label_8.setText("")
        self.tab3_win1label_8.setObjectName("tab3_win1label_8")
        self.tab3_win1label_5 = QtWidgets.QLabel(self.tab3_newWindow1)
        self.tab3_win1label_5.setGeometry(QtCore.QRect(20, 560, 41, 21))
        self.tab3_win1label_5.setObjectName("tab3_win1label_5")
        tab3_win1Main.setCentralWidget(self.tab3_newWindow1)

        self.retranslateUi(tab3_win1Main)
        QtCore.QMetaObject.connectSlotsByName(tab3_win1Main)

    def retranslateUi(self, tab3_win1Main):
        _translate = QtCore.QCoreApplication.translate
        tab3_win1Main.setWindowTitle(_translate("tab3_win1Main", "MainWindow"))
        self.tab3_win1tableWidget.setSortingEnabled(True)
        self.tab3_win1label.setText(_translate("tab3_win1Main", "펀드명:"))
        self.tab3_win1pushButton.setText(_translate("tab3_win1Main", "엑셀 변환"))
        self.tab3_win1label_3.setText(_translate("tab3_win1Main", "값:"))
        self.tab3_win1label_7.setText(_translate("tab3_win1Main", "합계:"))
        self.tab3_win1label_5.setText(_translate("tab3_win1Main", "갯수:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tab3_win1Main = QtWidgets.QMainWindow()
    ui = Ui_tab3_win1Main()
    ui.setupUi(tab3_win1Main)
    tab3_win1Main.show()
    sys.exit(app.exec_())
