# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowEarn.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tab3_win3ammain(object):
    def setupUi(self, tab3_win3ammain):
        tab3_win3ammain.setObjectName("tab3_win3ammain")
        tab3_win3ammain.resize(901, 561)
        self.tab3_newWindow3 = QtWidgets.QWidget(tab3_win3ammain)
        self.tab3_newWindow3.setObjectName("tab3_newWindow3")
        self.tab3_win3tableWidget = QtWidgets.QTableWidget(self.tab3_newWindow3)
        self.tab3_win3tableWidget.setGeometry(QtCore.QRect(0, 60, 901, 501))
        self.tab3_win3tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab3_win3tableWidget.setAlternatingRowColors(True)
        self.tab3_win3tableWidget.setObjectName("tab3_win3tableWidget")
        self.tab3_win3tableWidget.setColumnCount(0)
        self.tab3_win3tableWidget.setRowCount(0)
        self.tab3_win3label = QtWidgets.QLabel(self.tab3_newWindow3)
        self.tab3_win3label.setGeometry(QtCore.QRect(5, 10, 41, 20))
        self.tab3_win3label.setObjectName("tab3_win3label")
        self.tab3_win3label_2 = QtWidgets.QLabel(self.tab3_newWindow3)
        self.tab3_win3label_2.setGeometry(QtCore.QRect(53, 10, 271, 20))
        self.tab3_win3label_2.setAutoFillBackground(True)
        self.tab3_win3label_2.setText("")
        self.tab3_win3label_2.setObjectName("tab3_win3label_2")
        self.tab3_win3label_3 = QtWidgets.QLabel(self.tab3_newWindow3)
        self.tab3_win3label_3.setGeometry(QtCore.QRect(5, 32, 51, 20))
        self.tab3_win3label_3.setObjectName("tab3_win3label_3")
        self.tab3_win3comboBox = QtWidgets.QComboBox(self.tab3_newWindow3)
        self.tab3_win3comboBox.setGeometry(QtCore.QRect(56, 31, 121, 22))
        self.tab3_win3comboBox.setObjectName("tab3_win3comboBox")
        self.tab3_win3pushButton_2 = QtWidgets.QPushButton(self.tab3_newWindow3)
        self.tab3_win3pushButton_2.setGeometry(QtCore.QRect(740, 34, 51, 21))
        self.tab3_win3pushButton_2.setObjectName("tab3_win3pushButton_2")
        self.tab3_win3pushButton = QtWidgets.QPushButton(self.tab3_newWindow3)
        self.tab3_win3pushButton.setGeometry(QtCore.QRect(794, 34, 61, 21))
        self.tab3_win3pushButton.setObjectName("tab3_win3pushButton")
        self.tab3_win3dateEdit_2 = QtWidgets.QDateEdit(self.tab3_newWindow3)
        self.tab3_win3dateEdit_2.setEnabled(True)
        self.tab3_win3dateEdit_2.setGeometry(QtCore.QRect(460, 32, 91, 21))
        self.tab3_win3dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 11, 8), QtCore.QTime(0, 0, 0)))
        self.tab3_win3dateEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.tab3_win3dateEdit_2.setCalendarPopup(True)
        self.tab3_win3dateEdit_2.setObjectName("tab3_win3dateEdit_2")
        self.tab3_win3checkBox_2 = QtWidgets.QCheckBox(self.tab3_newWindow3)
        self.tab3_win3checkBox_2.setGeometry(QtCore.QRect(440, 32, 16, 21))
        self.tab3_win3checkBox_2.setText("")
        self.tab3_win3checkBox_2.setChecked(True)
        self.tab3_win3checkBox_2.setObjectName("tab3_win3checkBox_2")
        self.tab3_win3dateEdit = QtWidgets.QDateEdit(self.tab3_newWindow3)
        self.tab3_win3dateEdit.setEnabled(True)
        self.tab3_win3dateEdit.setGeometry(QtCore.QRect(310, 32, 91, 21))
        self.tab3_win3dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 11, 8), QtCore.QTime(0, 0, 0)))
        self.tab3_win3dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.tab3_win3dateEdit.setCalendarPopup(True)
        self.tab3_win3dateEdit.setObjectName("tab3_win3dateEdit")
        self.tab3_win3label_4 = QtWidgets.QLabel(self.tab3_newWindow3)
        self.tab3_win3label_4.setGeometry(QtCore.QRect(415, 32, 16, 21))
        self.tab3_win3label_4.setObjectName("tab3_win3label_4")
        self.tab3_win3checkBox = QtWidgets.QCheckBox(self.tab3_newWindow3)
        self.tab3_win3checkBox.setGeometry(QtCore.QRect(290, 32, 16, 21))
        self.tab3_win3checkBox.setText("")
        self.tab3_win3checkBox.setChecked(True)
        self.tab3_win3checkBox.setObjectName("tab3_win3checkBox")
        self.tab3_win3pushButton_3 = QtWidgets.QPushButton(self.tab3_newWindow3)
        self.tab3_win3pushButton_3.setGeometry(QtCore.QRect(859, 34, 41, 21))
        self.tab3_win3pushButton_3.setObjectName("tab3_win3pushButton_3")
        self.tab3_win3label_5 = QtWidgets.QLabel(self.tab3_newWindow3)
        self.tab3_win3label_5.setGeometry(QtCore.QRect(189, 33, 31, 20))
        self.tab3_win3label_5.setObjectName("tab3_win3label_5")
        self.tab3_win3comboBox_2 = QtWidgets.QComboBox(self.tab3_newWindow3)
        self.tab3_win3comboBox_2.setGeometry(QtCore.QRect(220, 32, 51, 22))
        self.tab3_win3comboBox_2.setObjectName("tab3_win3comboBox_2")
        tab3_win3ammain.setCentralWidget(self.tab3_newWindow3)

        self.retranslateUi(tab3_win3ammain)
        QtCore.QMetaObject.connectSlotsByName(tab3_win3ammain)

    def retranslateUi(self, tab3_win3ammain):
        _translate = QtCore.QCoreApplication.translate
        tab3_win3ammain.setWindowTitle(_translate("tab3_win3ammain", "MainWindow"))
        self.tab3_win3tableWidget.setSortingEnabled(False)
        self.tab3_win3label.setText(_translate("tab3_win3ammain", "펀드명:"))
        self.tab3_win3label_3.setText(_translate("tab3_win3ammain", "수익자"))
        self.tab3_win3pushButton_2.setText(_translate("tab3_win3ammain", "그래프"))
        self.tab3_win3pushButton.setText(_translate("tab3_win3ammain", "엑셀 변환"))
        self.tab3_win3label_4.setText(_translate("tab3_win3ammain", "~"))
        self.tab3_win3pushButton_3.setText(_translate("tab3_win3ammain", "조회"))
        self.tab3_win3label_5.setText(_translate("tab3_win3ammain", "구좌"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tab3_win3ammain = QtWidgets.QMainWindow()
    ui = Ui_tab3_win3ammain()
    ui.setupUi(tab3_win3ammain)
    tab3_win3ammain.show()
    sys.exit(app.exec_())
